version: 0.0
os: linux

files:
  - source: /
    destination: /usr/share/nginx/html/

hooks:
  BeforeInstall:
    - location: scripts/setup_nginx.sh
      timeout: 300
      runas: root

  Install:
    - location: scripts/noop.sh
      timeout: 300
      runas: root
