phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - |
        for i in {1..3}; do
          pip install -r requirements.txt && break || sleep 15
        done
